import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset, SidebarProvider } from "@/ui/shadcn/sidebar";
import { buildAdminNavigation } from "@/config/navigation.config";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Navika Admin",
  description: "Generated by create next app",
};


export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nav = buildAdminNavigation();
  return (
    <SidebarProvider
      style={
        {
          "--sidebar-width": "calc(var(--spacing) * 72)",
          "--header-height": "calc(var(--spacing) * 12)",
        } as React.CSSProperties
      }
    >
      <AppSidebar
        variant="inset"
        brand={nav.brand}
        navMainItems={nav.navMain}
        navSecondaryItems={nav.navSecondary}
      />
      <SidebarInset>
        <SiteHeader />
        <div className="flex flex-1 flex-col">
          <div className="@container/main flex flex-1 flex-col gap-2">
            <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
              {children}
            </div>
          </div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
